import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useRef, useState } from "react";

export default function Header() {
  const router = useRouter();
  const [showHeader, setShowHeader] = useState(true);
  const prevScrollY = useRef(0);
  const opacity = showHeader ? 0.8 : 0.5;
  const translateY = showHeader ? "0" : "-90px";
  const transition = showHeader
    ? "opacity 0.1s ease, transform 0.5s ease"
    : "opacity 0.1s ease 0.5s, transform 0.5s ease 0.5s";

  useEffect(() => {
    function handleScroll() {
      const currentScrollY = window.scrollY;
      if (prevScrollY.current < currentScrollY && showHeader) {
        setShowHeader(false);
      } else if (prevScrollY.current > currentScrollY && !showHeader) {
        setShowHeader(true);
      } else if (currentScrollY === 0) {
        setShowHeader(true);
      }
      prevScrollY.current = currentScrollY;
    }
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, [showHeader]);

  return (
    <>
      <Head>
        <title>Ժամանակակից Գրականություն</title>
        <meta
          name="description"
          content="Generated by Ժամանակակից Գրականություն"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div
        className="flex justify-center items-center w-full h-[50px] md:h-[90px] opacity-80 border-b border-[#e8e6f0] bg-white fixed top-0 left-0 z-50 md:max-w-full shadow-sm transition-all duration-300 ease-in-out dark:bg-gray-600"
        style={{
          transform: `translateY(${translateY})`,
          opacity,
          transition,
        }}
      >
        <p
          className="flex w-full cursor-pointer justify-center text-center items-center text-lg md:text-4xl font-bold font-serif"
          onClick={() => router.push("/")}
        >
          Ժամանակակից Գրականություն
        </p>
      </div>
    </>
  );
}
