import { useEffect, useState } from "react";
import Head from "next/head";
import { FaInstagram, FaLinkedin, FaGithub } from "react-icons/fa";
import { useRouter } from "next/router";
import { logger } from "@/utils/logger";
import { firestore } from "@/firebase";
import { collection, orderBy, query, limit, getDocs } from "firebase/firestore";

interface Score {
  id: string;
  score: number;
  username: string;
}

const MAX_SCORES = 10;

export default function Leaderboard() {
  const [topScores, setTopScores] = useState<Score[]>([]);
  const router = useRouter();

  const getTopScoresFromFirestore = async () => {
    try {
      const q = query(
        collection(firestore, "scores"),
        orderBy("score", "desc"),
        limit(MAX_SCORES)
      );
      const querySnapshot = await getDocs(q);
      const scores = querySnapshot.docs.map((doc) => ({
        id: doc.id,
        username: doc.data().username,
        score: doc.data().score,
      }));
      setTopScores(scores);
    } catch (e) {
      logger.error("Error getting top scores: ", e);
    }
  };

  useEffect(() => {
    getTopScoresFromFirestore();
  }, [topScores]);

  return (
    <>
      <Head>
        <title>Ժամանակակից Գրականություն</title>
        <meta
          name="description"
          content="Generated by Ժամանակակից Գրականություն"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="flex flex-col justify-center items-center w-full min-h-screen md:px-36 md:max-w-full overflow-hidden bg-[#f6f5f5] dark:bg-gray-500">
        <div className="flex justify-center items-center w-full h-[50px] md:h-[90px] opacity-80 border-b border-[#e8e6f0] bg-white fixed top-0 left-0 z-50 md:max-w-full shadow-sm dark:bg-gray-600">
          <p
            className="flex w-full cursor-pointer justify-center text-center items-center text-lg md:text-4xl font-bold font-serif"
            onClick={() => router.push("/")}
          >
            Ժամանակակից Գրականություն
          </p>
        </div>
        <div className="items-center justify-center text-center">
          <h2 className="text-4xl font-bold mb-8 text-[#1f36ff] mt-14 md:mt-24">
            Լավագույն 10 Խաղացողներ
          </h2>
          <table className="w-full mt-10 shadow-xl">
            <thead className="border-b h-10 bg-gray-300 dark:bg-gray-700">
              <tr>
                <th className="border-b h-10">Տեղ</th>
                <th className="border-b h-10">Անուն</th>
                <th className="border-b h-10">Միավոր</th>
              </tr>
            </thead>
            <tbody>
              {topScores.map((score, index) => (
                <tr key={score.id}>
                  <td className="border-b h-10">{index + 1}</td>
                  <td className="border-b h-10">{score.username}</td>
                  <td className="border-b h-10">{score.score}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <button
            className="items-center justify-center text-white text-xl bg-[#606ff8] mt-10 mb-10 rounded-lg w-48 h-16 hover:bg-[#aab2ff]"
            onClick={() => router.push("/game")}
          >
            Հետ Գնալ
          </button>
        </div>
      </div>
      <footer className="flex flex-col bg-gray-800 py-8 px-10 gap-4">
        <div className="flex flex-row flex-wrap md:flex-nowrap w-full">
          <div className="flex flex-row flex-shrink-0 text-gray-400 gap-2">
            <p className="text-left font-semibold text-gray-400">Created by:</p>
            <p className="text-left font-medium text-gray-400">
              Artur Karapetyan
            </p>
          </div>
          <div className="w-full">
            <p className="text-left md:text-right text-gray-400">
              © 2023 Armenian Language and Literature Final Project. All rights
              reserved.
            </p>
          </div>
        </div>
        <div className="flex flex-row justify-start gap-4">
          <a
            href="https://www.instagram.com/_arthur_karapetian_/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <FaInstagram size={24} color="white" />
          </a>
          <a
            href="https://www.linkedin.com/in/arturkarapetian/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <FaLinkedin size={24} color="white" />
          </a>
          <a
            href="https://github.com/artur-karapetyan"
            target="_blank"
            rel="noopener noreferrer"
          >
            <FaGithub size={24} color="white" />
          </a>
        </div>
      </footer>
    </>
  );
}
