import Head from "next/head";
import { useState, useEffect } from "react";

interface Book {
  title: string;
  author: string;
  description: string;
  rating: number;
}

export default function Books() {
  const [books, setBooks] = useState<Book[]>([]);

  useEffect(() => {
    const getBooks = async () => {
      const res = await fetch("/books.json");
      const data = await res.json();
      setBooks(data);
    };

    getBooks();
  }, []);

  return (
    <>
      <Head>
        <title>Ժամանակակից Գրականություն</title>
        <meta
          name="description"
          content="Generated by Ժամանակակից Գրականություն"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="flex flex-row justify-start items-center w-full h-full gap-10 px-[150px] pt-[100px] pb-[50px] bg-[#f6f5f5]">
        <div className="flex flex-wrap justify-start items-start flex-grow-0 flex-shrink-0 w-full h-full overflow-hidden gap-2.5">
          {books.map((book) => (
            <div
              className="flex flex-col justify-start items-center flex-grow-0 flex-shrink-0 w-[285px] h-[390px] overflow-hidden gap-2.5 p-2.5 border border-[#f4c785]"
              key={book.title}
            >
              <p>{book.title}</p>
              <p>{book.author}</p>
            </div>
          ))}
        </div>
      </div>
      <footer className="bg-gray-800 py-8">
        <div className="container mx-auto px-4">
          <p className="text-center text-gray-400">
            © 2023 My Book Website. All rights reserved.
          </p>
        </div>
      </footer>
    </>
  );
}
